services:
  web:
    build: .
    image: hardsub-ocr
    ports:
      - "7415:7415"
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials
      - videos:/app/videos
      - frames:/app/frames
      - results:/app/results
    depends_on:
      - redis
  worker:
    image: hardsub-ocr
    command: celery -A celery_app worker
    volumes:
      - videos:/app/videos
      - frames:/app/frames
      - results:/app/results
    depends_on:
      - redis
  redis:
    image: redis:alpine
volumes:
  videos:
  frames:
  results:
